### ISSUE TITLE
New note's titles are created with a leading space

### ISSUE THREAD

**Issue by EduPereyra** [BelkaDev/KRunner-Joplin-plugin#1]
Hi! First of all, thank you for sharing this excellent plugin! 

When I create a new note through krunner, the title is created with a leading space. For example, if I run `note personal/test` in krunner, then the new note is created as " test" in joplin. 

Does the same happen to you? Thanks in advance.

**Comment by BelkaDev** [comment]
Hi, I just fixed it. Thanks for your report.
