### ISSUE TITLE
ECONNREFUSED 127.0.0.1:42420

### ISSUE THREAD

**Issue by EduPereyra** [BelkaDev/KRunner-Joplin-plugin#2]
Hi again, 
I'm getting this error after updating Joplin to the latest version: 

`FetchError: request to http://localhost:42420/notes/open/26461a0fd68d4f2e9d54bd3e4747489d failed, reason: connect ECONNREFUSED 127.0.0.1:42420`
    `at ClientRequest.<anonymous> (/home/deflex/.local/share/kservices5/joplin-runner/node_modules/node-fetch/lib/index.js:1461:11)`
    `at ClientRequest.emit (node:events:394:28)`
     `at Socket.socketErrorListener (node:_http_client:447:9)`
     `at Socket.emit (node:events:394:28)`
    `at emitErrorNT (node:internal/streams/destroy:157:8)`
    `at emitErrorCloseNT (node:internal/streams/destroy:122:3)`
     `at processTicksAndRejections (node:internal/process/task_queues:83:21) {
   type: 'system',
   errno: 'ECONNREFUSED',
   code: 'ECONNREFUSED' 
   }
`

Maybe the plugin is not working with the latest version of Joplin?

**Comment by BelkaDev** [comment]
Hi,
Have you tried reinstalling the plugin?

**Comment by EduPereyra** [comment]
Hi, 
I did, several times. I forgot to mention that webclipper is working fine, if that helps.

**Comment by BelkaDev** [comment]
Thanks for reporting. I'll look into this when I get some spare time.

**Comment by BelkaDev** [comment]
This was fixed in the new plugin update
https://github.com/BelkaDev/joplin-send-action-plugin/releases
